### ISSUE TITLE
Dataframe references don't work after using splitstackshape

### ISSUE THREAD

**Issue by degovx** [mrdwab/splitstackshape#39]
Let's say I want to pull up columns 3 through 5 I would use dataframe[,3:5] which works perfectly. After using splitstackshape that same command returns [1] 3, 4, 5. If I run fix(dataframe) and close I can use the references again.

Here is a snippet showing the issue (using IMDB data):

> head(movies[,1:5])
          X                      Title Year Runtime                     Genre
tt0000439 1    The Great Train Robbery 1903      11            Short, Western
tt0003037 2      Juve Against Fantomas 1913      61              Crime, Drama
tt0003740 3                    Cabiria 1914     148 Adventure, Drama, History
tt0004707 4 Tillie's Punctured Romance 1914      82                    Comedy
tt0005960 5               Regeneration 1915      72   Biography, Crime, Drama
tt0006206 6               Les vampires 1915     399  Action, Adventure, Crime

> movies <- cSplit(movies, "Genre", sep=",")

> head(movies[,1:5])
[1] 1 2 3 4 5

> fix(movies)

> head(movies[,1:5])
  X                      Title Year Runtime   Released
1 1    The Great Train Robbery 1903      11 1903-12-01
2 2      Juve Against Fantomas 1913      61 1913-10-02
3 3                    Cabiria 1914     148 1914-06-01
4 4 Tillie's Punctured Romance 1914      82 1914-12-21
5 5               Regeneration 1915      72 1915-09-13
6 6               Les vampires 1915     399 1916-11-23

**Comment by mrdwab** [comment]
@degovx This is because `cSplit` returns an object of class `data.table` and `data.frame`. If you prefer to get back to `data.frame` functionality, you can use `setDF(movies)` to get your "movies" object back to just a "data.frame".

**Comment by mrdwab** [comment]
This is documented in the "Value" section of the documentation, but it might not be a bad idea to include an argument for `setDF`.
