### ISSUE TITLE
Whitespace regex and '_s' interaction

### ISSUE THREAD

**Issue by ajschol** [mrdwab/splitstackshape#48]
I'm seeing some weird interactions between using a regex to match on whitespacing and the characters '_s'.  
```R
d <- data.frame(id=1,list=c('a b_s ccc s_ddd eee_s fff s_g s_hhh iii'))
cSplit(d, c('list'), sep = "\\s", direction = "long", fixed = FALSE,
                 drop = TRUE, stripWhite = TRUE, makeEqual = FALSE,
                 type.convert = FALSE)
# WRONG:
#   id             list
#1:  1                a
#2:  1      b_scccs_ddd
#3:  1 eee_sfffs_gs_hhh
#4:  1              iii

# Contrast with
cSplit(d, c('list'), sep = " ", direction = "long", fixed = TRUE,
               drop = TRUE, stripWhite = TRUE, makeEqual = FALSE,
               type.convert = FALSE)
# As expected: 
#   id  list
#1:  1     a
#2:  1   b_s
#3:  1   ccc
#4:  1 s_ddd
#5:  1 eee_s
#6:  1   fff
#7:  1   s_g
#8:  1 s_hhh
#9:  1   iii

**Comment by mrdwab** [comment]
This requires `stripWhite = FALSE` with the `\\s` sep in order to work as expected.

    cSplit(d, c("list"), sep = "\\s", direction = "long", fixed = FALSE, 
        drop = TRUE, stripWhite = FALSE, makeEqual = FALSE, type.convert = FALSE)
    ##    id  list
    ## 1:  1     a
    ## 2:  1   b_s
    ## 3:  1   ccc
    ## 4:  1 s_ddd
    ## 5:  1 eee_s
    ## 6:  1   fff
    ## 7:  1   s_g
    ## 8:  1 s_hhh
    ## 9:  1   iii

In the [next version of `cSplit`](https://gist.github.com/mrdwab/a61efe8c201995633f30c7d7eaed40d4#file-fsplit-r), `stripWhite` won't be required for this.
