### ISSUE TITLE
Reshaping all columns

### ISSUE THREAD

**Issue by skanskan** [mrdwab/splitstackshape#49]
Hello.

How would you do this with splitstackshape?
https://stackoverflow.com/questions/41163500/r-transform-from-wide-to-long-without-sorting-columns

Transform from Wide to Long all columns with name "name_number" but without reordering/sorting the columns.

**Comment by mrdwab** [comment]
@skanskan , somehow I was never notified of this issue.

You can do this with `merged.stack`:

    merged.stack(mydata, var.stubs = c("ZA", "BB", "CC"), sep = "_")
    ##     ID .time_1 ZA BB CC
    ##  1:  1       1  1  3 NA
    ##  2:  1       2  5  6 NA
    ##  3:  1       7 NA NA  6
    ##  4:  2       1  2  3 NA
    ##  5:  2       2  4  6 NA
    ##  6:  2       7 NA NA  5
    ##  7:  3       1  3  3 NA
    ##  8:  3       2  3  6 NA
    ##  9:  3       7 NA NA  4
    ## 10:  4       1  4  3 NA
    ## 11:  4       2  2  6 NA
    ## 12:  4       7 NA NA  3
    ## 13:  5       1  5  3 NA
    ## 14:  5       2  1  6 NA
    ## 15:  5       7 NA NA  2

Also check out [this Gist](https://gist.github.com/mrdwab/ceded54b616bdc61cb0f) for something more efficient. With that, you could try:

     suppressWarnings(ReshapeLong_(mydata, stubs = c(ZA = "ZA_", BB = "BB_", CC = "CC_")))
