### ISSUE TITLE
cSplit: strange behaviour when only TT in column 

### ISSUE THREAD

**Issue by chrstraub** [mrdwab/splitstackshape#51]
Hi,

I noticed some strange behavior using cSplit.

My input (data) looks like this:

```
head(data)
      SNP1 SNP2 SNP3
1 AKL001   TT   CC   TT
2 AKL002   TT   CC   TT
3 BSC001   TT   CC   TT
4 BSC080   CT   CC   TT
5 BSC087   TT   CC   TT
6 BSC114   CT   CC   TT
```

`df<-cSplit(data, grep("SNP", names(data)) , "", stripWhite = FALSE)`

and the result is
```
head(df)
       V1 SNP1_1 SNP1_2 SNP2_1 SNP2_2 SNP3_1 SNP3_2
1: AKL001      T      T      C      C   TRUE   TRUE
2: AKL002      T      T      C      C   TRUE   TRUE
3: BSC001      T      T      C      C   TRUE   TRUE
4: BSC080      C      T      C      C   TRUE   TRUE
5: BSC087      T      T      C      C   TRUE   TRUE
6: BSC114      C      T      C      C   TRUE   TRUE
```

so it shows weird behavior when there is only TT present in the column. Any help would be appreciated!

**Comment by mrdwab** [comment]
@chrstraub , can you try adding `type.convert = FALSE` and see if the problem persists?

**Comment by mrdwab** [comment]
Using:

    mydf <- structure(list(ID = c("AKL001", "AKL002", "BSC001", "BSC080", 
        "BSC087", "BSC114"), SNP1 = c("TT", "TT", "TT", "CT", "TT", "CT"
        ), SNP2 = c("CC", "CC", "CC", "CC", "CC", "CC"), SNP3 = c("TT", 
        "TT", "TT", "TT", "TT", "TT")), .Names = c("ID", "SNP1", "SNP2", 
        "SNP3"), row.names = c("1", "2", "3", "4", "5", "6"), class = "data.frame")

And:

    cSplit(mydf, grep("SNP", names(mydf)), "", stripWhite = FALSE, type.convert = FALSE)

I get:

    ##        ID SNP1_1 SNP1_2 SNP2_1 SNP2_2 SNP3_1 SNP3_2
    ## 1: AKL001      T      T      C      C      T      T
    ## 2: AKL002      T      T      C      C      T      T
    ## 3: BSC001      T      T      C      C      T      T
    ## 4: BSC080      C      T      C      C      T      T
    ## 5: BSC087      T      T      C      C      T      T
    ## 6: BSC114      C      T      C      C      T      T

In [the next version of `cSplit`](https://gist.github.com/mrdwab/a61efe8c201995633f30c7d7eaed40d4) you won't need to use the `stripWhite` argument here, but you will still need to set `type.convert = FALSE`.

    cSplit_fread(mydf, grep("SNP", names(mydf)), "", type.convert = FALSE)
    ##        ID SNP1_1 SNP1_2 SNP2_1 SNP2_2 SNP3_1 SNP3_2
    ## 1: AKL001      T      T      C      C      T      T
    ## 2: AKL002      T      T      C      C      T      T
    ## 3: BSC001      T      T      C      C      T      T
    ## 4: BSC080      C      T      C      C      T      T
    ## 5: BSC087      T      T      C      C      T      T
    ## 6: BSC114      C      T      C      C      T      T
