### ISSUE TITLE
cSplit_f due to new fread argument structure

### ISSUE THREAD

**Issue by MichaelChirico** [mrdwab/splitstackshape#61]
`data.table` is getting ready for a new CRAN release that will break `cSplit_f`:

```
install.packages('data.table', type = 'source', repos = 'http://Rdatatable.github.io/data.table')
install.packages('splitstackshape', dependencies = TRUE)
library(splitstackshape)
example('cSplit_f')
# ...
cSplit_f(mydf, splitCols = c("v1", "v2", "v3"), sep = c("-", ".", "_"))
```

> Error in fread(x, sep[i], header = FALSE) : You can provide 'input=' or 'file=', not both.

You'll need to declare `sep = sep[i]` explicitly due to the new `file` argument coming second in `formals(fread)`.

Cheers

**Comment by mrdwab** [comment]
@MichaelChirico Thanks for the heads up. When is the CRAN update likely to happen?

**Comment by MichaelChirico** [comment]
I can't seem to find the thread, but ASAP. I believe CRAN informed us `data.table` must be updated by early May or face removal (!!)

Some discussion is here: https://github.com/Rdatatable/data.table/issues/2779

**Comment by mrdwab** [comment]
I'm traveling for the next two weeks, but will still try to find a computer and make the required change in the next few days.

**Comment by MichaelChirico** [comment]
Fret not, filed #62, hopefully you can easily just approve & merge from your phone 😃

**Comment by mattdowle** [comment]
Any luck with merging this please?  `splitstackshape` is error status on CRAN.

**Comment by mattdowle** [comment]
Thanks - 1.4.6 passing great now.  This issue can be closed.
