### ISSUE TITLE
cSplit_e column titles

### ISSUE THREAD

**Issue by mjahanshahi** [mrdwab/splitstackshape#66]
This is a fantastic package and I am so happy I found it.

When I ran cSplit_e, I noticed that the column titles reflect numbers. Is there a way to reflect the name of the contents of the column being split in the title?

For instance, I currently have a data frame with multiple IDs (about 180! For the sake of the example, its a characters such as 'blue', 'green', 'yellow', 'red'). I'd like the new column names to be the IDs, rather than arbitrary numbers (so Q2_blue, Q2_green). 

I looked through the docs and couldn't find anything that suggests this is possibility. Is there a helper function or a setting I can turn on?

**Comment by mjahanshahi** [comment]
Ah I figured it out. I just passed
`type = 'character'` to `cSplit_e`

**Comment by mrdwab** [comment]
@mjahanshahi , Glad it worked out :+1:
